### ISSUE TITLE
Error at /source/backend/cpu/arm/arm64/MNNVectorTop1Float.S.o

### ISSUE THREAD

**Issue by atbdeveloper** [Qengineering/Face-detection-Raspberry-Pi-32-64-bits#1]
Hi, greetings. I'm trying to compile MNN into Ubuntu 20.04 LTS running on Raspberry PI 4B and getting the following error:

[ 22%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S.o
/opt/mnn/MNN/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S: Assembler messages:
/opt/mnn/MNN/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S:35: Error: operand mismatch -- `mov v28.4s,v29.4s'
/opt/mnn/MNN/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S:35: Info:    did you mean this?
/opt/mnn/MNN/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S:35: Info:    	mov v28.8b, v29.8b
/opt/mnn/MNN/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S:35: Info:    other valid variant(s):
/opt/mnn/MNN/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S:35: Info:    	mov v28.16b, v29.16b
make[2]: *** [CMakeFiles/MNNARM64.dir/build.make:383: CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:597: CMakeFiles/MNNARM64.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Anyone know what could be happening?

**Comment by Qengineering** [comment]
This is a known issue of the latest tag 1.1.1 . See MNN github issue [#1310](https://github.com/alibaba/MNN/issues/1310)

You have two options.
Checkout version 1.1.0 which works fine on an ARM64.

Or
Modify file ~/MNN/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S line 34 ```mov v28.16b, v29.16b```
Modify file ~/MNN/source/backend/cpu/arm/arm64/MNNVectorTop1Int32.S line 34 ```mov v28.16b, v29.16b```
After successful compilation, I could run the benchmark examples. Probably this is the right fix for the issue. However it is not yet merged into the master branch, so still under testing. Future will tell.

**Comment by Qengineering** [comment]
MNN has fixed the issue in version 1.1.6 with the above modifications
