### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by kikirizki** [Qengineering/Face-detection-Raspberry-Pi-32-64-bits#3]
Hii Does MNN run faster than NCNN on small network?

**Comment by Qengineering** [comment]
In this case, indeed. MNN runs a lot faster than ncnn. Their model is better tuned, while ncnn uses a ported caffe model.
Most of the time, MNN and ncnn are running more or less at the same rate.

**Comment by kikirizki** [comment]
Thank you for your response
