### ISSUE TITLE
RPi 3 performance

### ISSUE THREAD

**Issue by tandy-1000** [Qengineering/Face-detection-Raspberry-Pi-32-64-bits#6]
I have not tested this yet, but I was wondering if you managed to compile and run this on a Pi 3/3B/3B+?

Unrelated question: do you know whether the model would perform the same in low light conditions or when using night vision cameras? In these cases sometimes the hue will be shifted.

Thank you.

**Comment by Qengineering** [comment]
Sure, no problem. Obvious, it will run somewhat slower.
Preferably, use a 64-bit OS for your Pi 3.

**Comment by tandy-1000** [comment]
Thanks for the super fast reply!
regarding my question on different hue / low light do you have any ideas?

**Comment by Qengineering** [comment]
Hue, low light are all related to pre-processing your image/video. The recognition will work under different lighting circumstances. 
However, the better the quality of the image, the more accurate your outcome will be. (A general rule for all vision systems)

**Comment by tandy-1000** [comment]
Another question do you know if the pi DNN image will work for Pi3? or will I have to install manually?

**Comment by Qengineering** [comment]
The Pi DNN image will only work with a RPi 4.
If you want to use the RPi 3, you have to install the several frameworks yourself.

**Comment by tandy-1000** [comment]
I had to also install these packages when using this [guide](https://qengineering.eu/install-mnn-on-raspberry-pi-4.html):
`$ sudo apt-get install build-essential gcc g++ git`

**Comment by Qengineering** [comment]
I've add them to the guide. Thanks!

**Comment by tandy-1000** [comment]
I've been able to compile the MNN/main.cpp, but I don't understand how I can use this?
It seems to only support running the model on a single video file, is it possible to run it on a camera input instead?

Edit: nevermind, I realised I can change the video name to 0 in line 19 and capture the camera, was able to compile successfully and test!
